# Generated by Django 3.2.19 on 2023-05-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangradsearchfields',
            name='tempo',
            field=models.IntegerField(),
        ),
    ]
