# Generated by Django 3.2.19 on 2024-01-01 23:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0002_discussion_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discuss',
            field=ckeditor.fields.RichTextField(max_length=100),
        ),
    ]
