# Generated by Django 3.2.19 on 2023-10-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0003_alter_discussion_forum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='SPOTIPY_APP.lodgeforum'),
        ),
    ]
