# Generated by Django 3.2.19 on 2023-05-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0003_discussion_lodgeforum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='LodgeForum',
            new_name='forum',
        ),
    ]
