# Generated by Django 3.2.19 on 2023-08-06 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0003_auto_20230727_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lodgeforum',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lodgeforum',
            name='name',
        ),
    ]
