# Generated by Django 3.2.19 on 2023-05-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0004_rename_lodgeforum_discussion_forum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='forum',
            new_name='LodgeForum',
        ),
    ]
