# Generated by Django 3.2.19 on 2023-08-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0004_auto_20230806_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgeforum',
            name='image',
            field=models.ImageField(null=True, upload_to='forum'),
        ),
        migrations.AlterField(
            model_name='lodgeforum',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
