# Generated by Django 3.2.19 on 2023-08-06 21:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPOTIPY_APP', '0005_auto_20230806_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lodgeforum',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='bangradsearchfields',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discussion',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lodgeforum',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
