# Generated by Django 3.2.19 on 2023-08-07 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SPOTIPY_APP', '0006_auto_20230806_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='lodgeforum',
            name='author',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
